### PR TITLE
K.java - Standardize/fix toString

### LINKED ISSUE #25: incorrect formatting for some simple lists in console view
e.g. "0Np 0Np 0Np" instead of "0N 0N 0Np"

### PR DESCRIPTION
**Pull request by punx120**
I took the test from https://github.com/CharlesSkelton/studio/pull/26 with some small adjustements

I also believe it may fix #25 

THE FOLLOWING DISCLAIMER APPLIES TO ALL SOFTWARE CODE AND OTHER MATERIALS CONTRIBUTED IN CONNECTION WITH THIS SOFTWARE:
THIS SOFTWARE IS LICENSED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS “AS IS” AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE AND ANY WARRANTY OF NON-INFRINGEMENT, ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE. THIS SOFTWARE MAY BE REDISTRIBUTED TO OTHERS ONLY BY EFFECTIVELY USING THIS OR ANOTHER EQUIVALENT DISCLAIMER IN ADDITION TO ANY OTHER REQUIRED LICENSE TERMS.
ONLY THE SOFTWARE CODE AND OTHER MATERIALS CONTRIBUTED IN CONNECTION WITH THIS SOFTWARE, IF ANY, THAT ARE ATTACHED TO (OR OTHERWISE ACCOMPANY) THIS SUBMISSION (AND ORDINARY COURSE CONTRIBUTIONS OF FUTURES PATCHES THERETO) ARE TO BE CONSIDERED A CONTRIBUTION. NO OTHER SOFTWARE CODE OR MATERIALS ARE A CONTRIBUTION.

### CODE REVIEW

File: src/test/studio/kdb/KTest.java [hunk 1]
```diff
@@ -104,4 +104,312 @@ public void testSymbolVector() {
...
+        check(new K.Projection((K.KList)vector(K.KList.class, funcBinary, new K.KLong(1), new K.UnaryPrimitive(-1))), "{x+y}[1;]", "{x+y}[1j;]");
+        check(new K.Projection((K.KList)vector(K.KList.class, funcBinary, new K.UnaryPrimitive(-1), new K.KLong(1))), "{x+y}[;1]", "{x+y}[;1j]");
+
+        check(new K.BinaryPrimitive(15), "~", "~");
+        check(new K.UnaryPrimitive(0), "::", "::");
+        check(new K.UnaryPrimitive(41), "enlist", "enlist");
+
+        //the output from +1
+        check(new K.Projection((K.KList)vector(K.KList.class, new K.BinaryPrimitive(1), new K.KLong(1))), "+[1]", "+[1j]");
+        //output from '[;]
```
Comment (punx120) [inline src/test/studio/kdb/KTest.java:406]: not sure what should be the output, orginal PR had `'[;]`, but origin code for kdb studio outputs `(';;)`

Comment (punx120) [reply src/test/studio/kdb/KTest.java:406]: similar comment for the 2 others "projections"

File: src/main/studio/kdb/K.java [hunk 2]
```diff
@@ -777,11 +799,11 @@ public boolean isNull() {
 
         public String toString(boolean showType) {
             if (isNull())
-                return "0Nd";
+                return "0nd";
```
Comment (gyorokpeter) [inline src/main/studio/kdb/K.java:802]: The convention is to use "n" for float and "N" for everything else. q will parse if you input the "n" with the wrong case but it will print the value back using the correct case. Same for w/W.
https://code.kx.com/q/basics/datatypes/

File: src/main/studio/kdb/K.java [hunk 3]
```diff
@@ -101,6 +101,18 @@ public Adverb(K.KBase o) {
         public Object getObject() {
             return o;
         }
+
+        @Override
+        public String toString(boolean showType) {
+            try {
+                LimitedWriter writer = new LimitedWriter(256);
```
Comment (gyorokpeter) [inline src/main/studio/kdb/K.java:108]: Why the limit of 256? What happens e.g. if the iterated function is a long lambda?

File: src/test/studio/kdb/KTest.java (hunk 1 above)
Comment (gyorokpeter) [reply src/test/studio/kdb/KTest.java:406]: The two have different meanings. ```'[;]``` is a projection of the ' operator with two missing arguments. ```(';;)``` is a projection of ```enlist``` with the first argument being ' and the second and third arguments elided. The first one seems to be more accurate.

File: src/main/studio/kdb/K.java (hunk 2 above)
Comment (punx120) [reply src/main/studio/kdb/K.java]: Thanks - updated the PR - everything is now upper case except KDouble

File: src/main/studio/kdb/K.java (hunk 3 above)
Comment (punx120) [reply src/main/studio/kdb/K.java:108]: no good reason, took this limit from the one used by CellRenderer. But we could increase to something bigger - do you have a strong opinion?

Comment (gyorokpeter) [reply src/main/studio/kdb/K.java:108]: Does there have to be a limit at all? Or what if you give it INT_MAX?

Comment (punx120) [reply src/main/studio/kdb/K.java:108]: I'm afraid it may lead  to some sort of memory issue if the string generated is really large. I think we we can start with something like 5,000 or so. It can't be worse than today where it doesn't _output_ anything...

File: src/test/studio/kdb/KTest.java (hunk 1 above)
Comment (punx120) [reply src/test/studio/kdb/KTest.java:406]: Fixed

File: src/main/studio/kdb/K.java (hunk 3 above)
Comment (punx120) [reply src/main/studio/kdb/K.java]: Updated in last commit

**Review by gyorokpeter — APPROVED** [review]
